FROM redcapcustodian

WORKDIR /home/rocker

ADD . /home/rocker/redcapcustodian

# Note where we are, what is there, and what's in the package dir
CMD pwd && ls -AlhF ./ && echo /home/rocker/redcapcustodian && ls -AlhF ./redcapcustodian
